[project]
name = "smartabasepy"
version = "0.1"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
     "requests", 
    "requests-toolbelt",
    "pandas", 
    "keyring",
    "os",
    "tqdm",
    "typing",
    "datetime",
    "hashlib",
    "mimetype"
]