name: Test smartabasepy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov responses python-dotenv
        pip install .
    - name: Run tests
      env:
        AMS_USERNAME: ${{ secrets.AMS_USERNAME }}
        AMS_PASSWORD: ${{ secrets.AMS_PASSWORD }}
        AMS_URL: ${{ secrets.AMS_URL }}
      run: pytest tests/ --cov=smartabasepy --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml